Document: cuihmne-jackmeter
Title: Debian cuihmne-jackmeter Manual
Author: <insert document author here>
Abstract: This manual describes what cuihmne-jackmeter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/cuihmne-jackmeter/cuihmne-jackmeter.sgml.gz

Format: postscript
Files: /usr/share/doc/cuihmne-jackmeter/cuihmne-jackmeter.ps.gz

Format: text
Files: /usr/share/doc/cuihmne-jackmeter/cuihmne-jackmeter.text.gz

Format: HTML
Index: /usr/share/doc/cuihmne-jackmeter/html/index.html
Files: /usr/share/doc/cuihmne-jackmeter/html/*.html
