name: build_package
on: [push]
jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Compile Code
        run: docker run -it -v `pwd`:/src debian bash -C "/src/build.sh"
      - uses: actions/upload-artifact@v3
        with:
          name: jack_meter
